default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: photo_development

test:
  <<: *default
  database: photo_test

production:
  <<: *default
  database: photo_production
